---
- name: Get Rancher Information
  hosts: control_plane
  become: no
  vars:
    kubeconfig_path: "~/.kube/{{ cluster_name }}-CONTROL-PLANE-NODE-1.yaml"
    rancher_hostname: "{{ rancher_hostname_var }}"
    rancher_bootstrap_password: "{{ rancher_password }}"

  tasks:
    - name: Get Rancher pod status
      shell: kubectl get pods -n cattle-system | grep rancher
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: rancher_pods

    - name: Display Rancher status
      debug:
        msg: "{{ rancher_pods.stdout_lines }}"

    - name: Display Rancher URL
      debug:
        msg: "Rancher URL: https://{{ rancher_hostname }}"

    - name: Display bootstrap password
      debug:
        msg: "Bootstrap Password: {{ rancher_bootstrap_password }}"
