---
all:
  vars:
    cluster_name: "rapidtest"
    cluster_env_domain: "mosip.local"
    k8s_infra_repo_url: "https://github.com/mosip/k8s-infra.git"
    k8s_infra_branch: "v1.2.1.0"
    install_rke2_version: "v1.28.9+rke2r1"
    enable_rancher_import: true
    rancher_import_url: "kubectl apply -f https://rancher.mosip.net/v3/import/vzfc46l2crb4q6qt29ds66qswszs4b5sbk7mpz5s7d6vdct9ktjmnr_c-m-qwggjk4x.yaml"
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ./ssh_key
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
  children:
    control_plane:
      hosts:
        rapidtest-CONTROL-PLANE-NODE-1:
          ansible_host: 172.31.66.52
          node_role: control_plane
          is_primary: true
          node_index: 0
        rapidtest-CONTROL-PLANE-NODE-2:
          ansible_host: 172.31.78.12
          node_role: control_plane
          is_primary: false
          node_index: 1
        rapidtest-CONTROL-PLANE-NODE-3:
          ansible_host: 172.31.72.72
          node_role: control_plane
          is_primary: false
          node_index: 2
    
    etcd:
      hosts:
        rapidtest-ETCD-NODE-1:
          ansible_host: 172.31.66.93
          node_role: etcd
        rapidtest-ETCD-NODE-2:
          ansible_host: 172.31.69.220
          node_role: etcd
        rapidtest-ETCD-NODE-3:
          ansible_host: 172.31.79.24
          node_role: etcd
    
    workers:
      hosts:
        rapidtest-WORKER-NODE-1:
          ansible_host: 172.31.67.253
          node_role: worker
        rapidtest-WORKER-NODE-2:
          ansible_host: 172.31.78.156
          node_role: worker

    rke2_cluster:
      children:
        control_plane:
        etcd:
        workers:
