---
all:
  vars:
    cluster_name: "ab13"
    cluster_env_domain: "mosip.local"
    k8s_infra_repo_url: "https://github.com/mosip/k8s-infra.git"
    k8s_infra_branch: "release-1.2.1.x"
    install_rke2_version: "v1.28.9+rke2r1"
    enable_rancher_import: true
    rancher_import_url: "kubectl apply -f https://rancher.mosip.net/v3/import/94mdxbtbb2vqf5kh6h6mjdcx49t7h9m2fdh5t7df78t9z7qk9nzm8p_c-m-2fk99m9b.yaml"
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ./ssh_key
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
  children:
    control_plane:
      hosts:
        ab13-CONTROL-PLANE-NODE-1:
          ansible_host: 172.31.73.166
          node_role: control_plane
          is_primary: true
          node_index: 0
    
    etcd:
      hosts:
        ab13-ETCD-NODE-1:
          ansible_host: 172.31.64.223
          node_role: etcd
    
    workers:
      hosts:
        ab13-WORKER-NODE-1:
          ansible_host: 172.31.76.37
          node_role: worker
        ab13-WORKER-NODE-2:
          ansible_host: 172.31.73.249
          node_role: worker

    rke2_cluster:
      children:
        control_plane:
        etcd:
        workers:
