---
all:
  vars:
    cluster_name: "devint1"
    cluster_env_domain: "mosip.local"
    k8s_infra_repo_url: "https://github.com/mosip/k8s-infra.git"
    k8s_infra_branch: "develop"
    install_rke2_version: "v1.28.9+rke2r1"
    enable_rancher_import: true
    rancher_import_url: "kubectl apply -f https://rancher.observation.mosip.net/v3/import/kdghv4kkfc24nlm4wvkmmcdt7ch5dxdrrp2g6tq46zjlq65pdnqmhm_c-m-wkfp4vbk.yaml"
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ./ssh_key
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
  children:
    control_plane:
      hosts:
        devint1-CONTROL-PLANE-NODE-1:
          ansible_host: 10.0.4.206
          node_role: control_plane
          is_primary: true
          node_index: 0
        devint1-CONTROL-PLANE-NODE-2:
          ansible_host: 10.0.4.54
          node_role: control_plane
          is_primary: false
          node_index: 1
        devint1-CONTROL-PLANE-NODE-3:
          ansible_host: 10.0.4.139
          node_role: control_plane
          is_primary: false
          node_index: 2
    
    etcd:
      hosts:
        devint1-ETCD-NODE-1:
          ansible_host: 10.0.4.164
          node_role: etcd
        devint1-ETCD-NODE-2:
          ansible_host: 10.0.4.184
          node_role: etcd
        devint1-ETCD-NODE-3:
          ansible_host: 10.0.4.18
          node_role: etcd
    
    workers:
      hosts:
        devint1-WORKER-NODE-1:
          ansible_host: 10.0.4.63
          node_role: worker
        devint1-WORKER-NODE-2:
          ansible_host: 10.0.4.171
          node_role: worker
        devint1-WORKER-NODE-3:
          ansible_host: 10.0.4.247
          node_role: worker

    rke2_cluster:
      children:
        control_plane:
        etcd:
        workers:
