apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grafana
spec:
  selector:
    istio: ingressgateway-internal
  servers:
  - port:
      number: 80
      name: grafana
      protocol: HTTP
    hosts:
    - {{ .Values.grafanaHost }}
