apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
spec:
  hosts:
  - {{ .Values.grafanaHost }}
  gateways:
    {{- if .Values.gateways.internal.enabled }}
    - grafana
    {{- end }}
    {{- if .Values.gateways.public.enabled }}
    - grafana-public
    {{- end }}
  http:
  - route:
    - destination:
        host: {{ .Values.installName }}
        port:
          number: {{ .Values.grafanaPort | int }}
    headers:
      request:
        set:
          x-forwarded-proto: https
