# ActiveMQ EBS Volume Setup Module
# Runs Ansible on the Terraform RUNNER machine, which SSHes into the NGINX node.
# 1. Formats + mounts the 3rd EBS volume on the NGINX node
# 2. Configures NFS export for Kubernetes pod access
# 3. Generates and applies a Kubernetes StorageClass for the NFS share

variable "NGINX_PUBLIC_IP" { type = string }
variable "NGINX_PRIVATE_IP" { type = string }
variable "SSH_PRIVATE_KEY" {
  type        = string
  sensitive   = true
  description = "SSH private key content for connecting to nodes"
}
variable "NGINX_NODE_EBS_VOLUME_SIZE_3" { type = number }

variable "ACTIVEMQ_STORAGE_DEVICE" {
  type        = string
  default     = "/dev/nvme3n1"
  description = "Block device path of the 3rd EBS volume"
}
variable "ACTIVEMQ_MOUNT_POINT" {
  type        = string
  default     = "/srv/activemq"
  description = "Mount point for ActiveMQ persistent storage (also the NFS share path)"
}

# Kubernetes Control Plane — for applying the StorageClass
variable "CONTROL_PLANE_HOST" {
  type        = string
  description = "IP address of the Kubernetes control plane node"
}
variable "CONTROL_PLANE_USER" {
  type        = string
  default     = "ubuntu"
  description = "SSH username for control plane access"
}

# ── Resource 1: EBS Volume + NFS Setup (runs Ansible on the Terraform runner) ──
resource "null_resource" "activemq-ebs-nfs-setup" {
  count = var.NGINX_NODE_EBS_VOLUME_SIZE_3 > 0 ? 1 : 0

  triggers = {
    # Re-run when target node is replaced (new IP = new instance)
    nginx_private_ip = var.NGINX_PRIVATE_IP

    # Re-run when storage configuration changes
    device_mount_hash = md5("${var.ACTIVEMQ_STORAGE_DEVICE}${var.ACTIVEMQ_MOUNT_POINT}")
  }

  # Write the SSH private key to a temp file on the runner, then run Ansible locally.
  # Ansible SSHes into the NGINX node using that key.
  provisioner "local-exec" {
    # SECURITY: The SSH private key is passed via environment variable, NOT
    # interpolated in the command string. This prevents it from appearing in:
    #   - Terraform plan/apply output
    #   - Shell history (ps aux, /proc)
    #   - CI/CD logs that capture stdout
    # The script reads TF_ACTIVEMQ_SSH_KEY and writes it to a chmod-600 temp file.
    command     = <<-EOT
      set -euo pipefail

      # ── Write SSH key from env var (never from command args) ──────────────────
      KEY_FILE=$(mktemp /tmp/activemq-ssh-key-XXXXXX)
      chmod 600 "$KEY_FILE"
      # Use printf to avoid trailing newline issues with echo
      printf '%s' "$TF_ACTIVEMQ_SSH_KEY" > "$KEY_FILE"

      # ── Copy playbook to a temp working dir ───────────────────────────────────
      WORK_DIR=$(mktemp -d /tmp/activemq-setup-XXXXXX)

      # ── Guarantee cleanup of KEY_FILE and WORK_DIR on success or failure ──────
      trap 'rm -rf "$KEY_FILE" "$WORK_DIR"' EXIT ERR

      cp "${path.module}/activemq-setup.yml" "$WORK_DIR/activemq-setup.yml"
      cp "${path.module}/activemq-setup.sh"  "$WORK_DIR/activemq-setup.sh"
      chmod +x "$WORK_DIR/activemq-setup.sh"

      # ── Run the setup script (Ansible runs on this runner, SSHes into NGINX) ──
      export NGINX_PRIVATE_IP="${var.NGINX_PRIVATE_IP}"
      export ACTIVEMQ_STORAGE_DEVICE="${var.ACTIVEMQ_STORAGE_DEVICE}"
      export ACTIVEMQ_MOUNT_POINT="${var.ACTIVEMQ_MOUNT_POINT}"
      export SSH_KEY_FILE="$KEY_FILE"
      export WORK_DIR="$WORK_DIR"

      bash "$WORK_DIR/activemq-setup.sh"
    EOT
    interpreter = ["bash", "-c"]

    environment = {
      # Key passed as env var — never appears in command string or Terraform logs
      TF_ACTIVEMQ_SSH_KEY = var.SSH_PRIVATE_KEY
    }
  }
}

# ── Resource 2: Apply StorageClass to Kubernetes ──────────────────────────────
# The Ansible playbook generates /tmp/activemq-storageclass.yaml on the runner.
# This resource copies it to the K8s control plane and applies it.
resource "null_resource" "activemq-k8s-storageclass" {
  count      = var.NGINX_NODE_EBS_VOLUME_SIZE_3 > 0 ? 1 : 0
  depends_on = [null_resource.activemq-ebs-nfs-setup]

  connection {
    type        = "ssh"
    host        = var.CONTROL_PLANE_HOST
    user        = var.CONTROL_PLANE_USER
    private_key = var.SSH_PRIVATE_KEY
    timeout     = "10m"
    agent       = false
  }

  # Copy the StorageClass YAML (generated by Ansible on the runner) to control plane
  provisioner "file" {
    source      = "/tmp/activemq-storageclass.yaml"
    destination = "/tmp/activemq-storageclass.yaml"
  }

  # Apply it to the cluster
  provisioner "remote-exec" {
    inline = [
      # Build kubeconfig path from the actual login user using find to locate the .yaml file
      "export KUBECONFIG=$(find /home/${var.CONTROL_PLANE_USER}/.kube/ -name '*.yaml' | head -1)",
      # Fail immediately with a clear message if no valid file was found.
      "if [ -z \"$KUBECONFIG\" ] || [ ! -f \"$KUBECONFIG\" ]; then echo \"ERROR: kubeconfig not found in /home/${var.CONTROL_PLANE_USER}/.kube/\"; exit 1; fi",
      "echo 'Using kubeconfig: $KUBECONFIG'",
      "kubectl cluster-info",
      "echo 'Applying ActiveMQ NFS StorageClass...'",
      "kubectl apply -f /tmp/activemq-storageclass.yaml",
      "echo 'Verifying StorageClass was created...'",
      "kubectl get storageclass nfs-csi-activemq",
      "rm -f /tmp/activemq-storageclass.yaml"
    ]
  }
}
