# ActiveMQ EBS Volume Setup Module
# Runs Ansible on the Terraform RUNNER machine, which SSHes into the NGINX node.
# 1. Formats + mounts the 3rd EBS volume on the NGINX node
# 2. Configures NFS export for Kubernetes pod access
# 3. Generates and applies a Kubernetes StorageClass for the NFS share

variable "NGINX_PUBLIC_IP" { type = string }
variable "NGINX_PRIVATE_IP" { type = string }
variable "SSH_PRIVATE_KEY" { type = string }
variable "NGINX_NODE_EBS_VOLUME_SIZE_3" { type = number }

variable "ACTIVEMQ_STORAGE_DEVICE" {
  type        = string
  default     = "/dev/nvme3n1"
  description = "Block device path of the 3rd EBS volume"
}
variable "ACTIVEMQ_MOUNT_POINT" {
  type        = string
  default     = "/srv/activemq"
  description = "Mount point for ActiveMQ persistent storage (also the NFS share path)"
}

# Kubernetes Control Plane — for applying the StorageClass
variable "CONTROL_PLANE_HOST" {
  type        = string
  description = "IP address of the Kubernetes control plane node"
}
variable "CONTROL_PLANE_USER" {
  type        = string
  default     = "ubuntu"
  description = "SSH username for control plane access"
}

# ── Resource 1: EBS Volume + NFS Setup (runs Ansible on the Terraform runner) ──
resource "null_resource" "activemq-ebs-nfs-setup" {
  count = var.NGINX_NODE_EBS_VOLUME_SIZE_3 > 0 ? 1 : 0

  triggers = {
    device_mount_hash = md5("${var.ACTIVEMQ_STORAGE_DEVICE}${var.ACTIVEMQ_MOUNT_POINT}")
  }

  # Write the SSH private key to a temp file on the runner, then run Ansible locally.
  # Ansible SSHes into the NGINX node using that key.
  provisioner "local-exec" {
    command     = <<-EOT
      set -euo pipefail

      # ── Write the SSH private key ──────────────────────────────────────────────
      KEY_FILE=$(mktemp /tmp/activemq-ssh-key-XXXXXX)
      chmod 600 "$KEY_FILE"
      cat > "$KEY_FILE" <<'SSHKEY'
${var.SSH_PRIVATE_KEY}
SSHKEY

      # ── Copy playbook to a temp working dir ───────────────────────────────────
      WORK_DIR=$(mktemp -d /tmp/activemq-setup-XXXXXX)
      cp "${path.module}/activemq-setup.yml" "$WORK_DIR/activemq-setup.yml"
      cp "${path.module}/activemq-setup.sh"  "$WORK_DIR/activemq-setup.sh"
      chmod +x "$WORK_DIR/activemq-setup.sh"

      # ── Run the setup script (Ansible runs on this runner, SSHes into NGINX) ──
      export NGINX_PRIVATE_IP="${var.NGINX_PRIVATE_IP}"
      export ACTIVEMQ_STORAGE_DEVICE="${var.ACTIVEMQ_STORAGE_DEVICE}"
      export ACTIVEMQ_MOUNT_POINT="${var.ACTIVEMQ_MOUNT_POINT}"
      export SSH_KEY_FILE="$KEY_FILE"
      export WORK_DIR="$WORK_DIR"

      bash "$WORK_DIR/activemq-setup.sh"

      # ── Cleanup key ───────────────────────────────────────────────────────────
      rm -f "$KEY_FILE"
    EOT
    interpreter = ["bash", "-c"]
  }
}

# ── Resource 2: Apply StorageClass to Kubernetes ──────────────────────────────
# The Ansible playbook generates /tmp/activemq-storageclass.yaml on the runner.
# This resource copies it to the K8s control plane and applies it.
resource "null_resource" "activemq-k8s-storageclass" {
  count      = var.NGINX_NODE_EBS_VOLUME_SIZE_3 > 0 ? 1 : 0
  depends_on = [null_resource.activemq-ebs-nfs-setup]

  connection {
    type        = "ssh"
    host        = var.CONTROL_PLANE_HOST
    user        = var.CONTROL_PLANE_USER
    private_key = var.SSH_PRIVATE_KEY
    timeout     = "10m"
    agent       = false
  }

  # Copy the StorageClass YAML (generated by Ansible on the runner) to control plane
  provisioner "file" {
    source      = "/tmp/activemq-storageclass.yaml"
    destination = "/tmp/activemq-storageclass.yaml"
  }

  # Apply it to the cluster
  provisioner "remote-exec" {
    inline = [
      "export KUBECONFIG=$(find /home/ubuntu/.kube/ -name '*.yaml' | head -1)",
      "echo 'Using kubeconfig: $KUBECONFIG'",
      "kubectl cluster-info",
      "echo 'Applying ActiveMQ NFS StorageClass...'",
      "kubectl apply -f /tmp/activemq-storageclass.yaml",
      "echo 'Verifying StorageClass was created...'",
      "kubectl get storageclass nfs-csi-activemq",
      "rm -f /tmp/activemq-storageclass.yaml"
    ]
  }
}
