# ActiveMQ EBS Volume Setup Module
# 1. Formats + mounts the 3rd EBS volume on the NGINX node
# 2. Configures NFS export for Kubernetes pod access
# 3. Generates and applies a Kubernetes StorageClass for the NFS share

variable "NGINX_PUBLIC_IP" { type = string }
variable "NGINX_PRIVATE_IP" { type = string }
variable "SSH_PRIVATE_KEY" { type = string }
variable "NGINX_NODE_EBS_VOLUME_SIZE_3" { type = number }

variable "ACTIVEMQ_STORAGE_DEVICE" {
  type        = string
  default     = "/dev/nvme3n1"
  description = "Block device path of the 3rd EBS volume"
}
variable "ACTIVEMQ_MOUNT_POINT" {
  type        = string
  default     = "/srv/activemq"
  description = "Mount point for ActiveMQ persistent storage (also the NFS share path)"
}

# Kubernetes Control Plane — for applying the StorageClass
variable "CONTROL_PLANE_HOST" {
  type        = string
  description = "IP address of the Kubernetes control plane node"
}
variable "CONTROL_PLANE_USER" {
  type        = string
  default     = "ubuntu"
  description = "SSH username for control plane access"
}

# ── Resource 1: EBS Volume + NFS Setup on NGINX Node ─────────────────────────
resource "null_resource" "activemq-ebs-nfs-setup" {
  count = var.NGINX_NODE_EBS_VOLUME_SIZE_3 > 0 ? 1 : 0

  triggers = {
    device_mount_hash = md5("${var.ACTIVEMQ_STORAGE_DEVICE}${var.ACTIVEMQ_MOUNT_POINT}")
  }

  connection {
    type        = "ssh"
    host        = var.NGINX_PRIVATE_IP
    user        = "ubuntu"
    private_key = var.SSH_PRIVATE_KEY
    timeout     = "10m"
    agent       = false
  }

  provisioner "file" {
    source      = "${path.module}/activemq-setup.sh"
    destination = "/tmp/activemq-setup.sh"
  }

  provisioner "file" {
    source      = "${path.module}/activemq-setup.yml"
    destination = "/tmp/activemq-setup.yml"
  }

  provisioner "remote-exec" {
    inline = [
      "export ACTIVEMQ_STORAGE_DEVICE=${var.ACTIVEMQ_STORAGE_DEVICE}",
      "export ACTIVEMQ_MOUNT_POINT=${var.ACTIVEMQ_MOUNT_POINT}",
      "sudo chmod +x /tmp/activemq-setup.sh",
      "bash /tmp/activemq-setup.sh"
    ]
  }
}

# ── Resource 2: Apply StorageClass to Kubernetes ──────────────────────────────
# Copies the generated storageclass.yaml from the Terraform runner to the
# K8s control plane, then applies it — identical pattern to postgresql-k8s-deployment.
resource "null_resource" "activemq-k8s-storageclass" {
  count      = var.NGINX_NODE_EBS_VOLUME_SIZE_3 > 0 ? 1 : 0
  depends_on = [null_resource.activemq-ebs-nfs-setup]

  connection {
    type        = "ssh"
    host        = var.CONTROL_PLANE_HOST
    user        = var.CONTROL_PLANE_USER
    private_key = var.SSH_PRIVATE_KEY
    timeout     = "10m"
    agent       = false
  }

  # Copy the StorageClass YAML (generated by the playbook on localhost) to control plane
  provisioner "file" {
    source      = "/tmp/activemq-storageclass.yaml"
    destination = "/tmp/activemq-storageclass.yaml"
  }

  # Apply it to the cluster
  provisioner "remote-exec" {
    inline = [
      "export KUBECONFIG=$(find /home/ubuntu/.kube/ -name '*.yaml' | head -1)",
      "echo 'Using kubeconfig: $KUBECONFIG'",
      "kubectl cluster-info",
      "echo 'Applying ActiveMQ NFS StorageClass...'",
      "kubectl apply -f /tmp/activemq-storageclass.yaml",
      "echo 'Verifying StorageClass was created...'",
      "kubectl get storageclass nfs-csi-activemq",
      "rm -f /tmp/activemq-storageclass.yaml"
    ]
  }
}
