{{- if .Values.postgres.configmaps }}
{{- range $cm_name, $cm_value := .Values.postgres.configmaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cm_name }}
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "external-postgres-setup.labels" $ | nindent 4 }}
    {{- if $.Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $value := $cm_value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
