grafanaHost: grafana.sandbox.xyz.net
# Loki stack Grafana (not rancher-monitoring Grafana)
installName: grafana.loki-monitoring.svc.cluster.local
grafanaPort: 80
gateways:
  internal:
    enabled: true
    selector: ingressgateway-internal
  public:
    enabled: true
    selector: ingressgateway
