extraEnvVars:
  DATABASE_HOST:
    valueFrom:
      configMapKeyRef:
        name: mockid-postgres-config
        key: database-host
  DATABASE_PORT:
    valueFrom:
      configMapKeyRef:
        name: mockid-postgres-config
        key: database-port
  DATABASE_NAME:
    valueFrom:
      configMapKeyRef:
        name: mockid-postgres-config
        key: database-name
  DATABASE_USERNAME:
    valueFrom:
      configMapKeyRef:
        name: mockid-postgres-config
        key: database-username
  DB_DBUSER_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: db-common-secrets
        key: db-dbuser-password
  SOFTHSM_MOCK_IDENTITY_SYSTEM_SECURITY_PIN:
    valueFrom:
      secretKeyRef:
        name: softhsm-mock-identity-system-go
        key: security-pin
  hsm_local_dir_name: hsm-client
  MOSIP_ESIGNET_MOCK_SUPPORTED_FIELDS: individualId,password
  REDIS_HOST:
    valueFrom:
      configMapKeyRef:
        name: redis-config
        key: redis-host
  REDIS_PORT:
    valueFrom:
      configMapKeyRef:
        name: redis-config
        key: redis-port
  REDIS_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: redis
        key: redis-password
