apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dummy-postgres-setup.fullname" . }}-placeholder
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dummy-postgres-setup.labels" . | nindent 4 }}
data:
  purpose: "Placeholder for postgres namespace and hooks setup"
  created: {{ now | quote }}
  note: "This ConfigMap serves as a minimal resource to enable namespace creation and hook execution"
